# Generated by Django 5.2.1 on 2025-05-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_exit_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='entrance_day',
            new_name='entry_day',
        ),
    ]
